
package org.example.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.7
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GroupService", targetNamespace = "http://service.example.org/", wsdlLocation = "http://localhost:8888/myserv?wsdl")
public class GroupService
    extends Service
{

    private static final URL GROUPSERVICE_WSDL_LOCATION;
    private static final WebServiceException GROUPSERVICE_EXCEPTION;
    private static final QName GROUPSERVICE_QNAME = new QName("http://service.example.org/", "GroupService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/myserv?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GROUPSERVICE_WSDL_LOCATION = url;
        GROUPSERVICE_EXCEPTION = e;
    }

    public GroupService() {
        super(__getWsdlLocation(), GROUPSERVICE_QNAME);
    }

    public GroupService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GROUPSERVICE_QNAME, features);
    }

    public GroupService(URL wsdlLocation) {
        super(wsdlLocation, GROUPSERVICE_QNAME);
    }

    public GroupService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GROUPSERVICE_QNAME, features);
    }

    public GroupService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GroupService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Group
     */
    @WebEndpoint(name = "GroupPort")
    public Group getGroupPort() {
        return super.getPort(new QName("http://service.example.org/", "GroupPort"), Group.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Group
     */
    @WebEndpoint(name = "GroupPort")
    public Group getGroupPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.example.org/", "GroupPort"), Group.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GROUPSERVICE_EXCEPTION!= null) {
            throw GROUPSERVICE_EXCEPTION;
        }
        return GROUPSERVICE_WSDL_LOCATION;
    }

}
