
package org.example.client;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.7
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Group", targetNamespace = "http://service.example.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Group {


    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getnext", targetNamespace = "http://service.example.org/", className = "org.example.client.Getnext")
    @ResponseWrapper(localName = "getnextResponse", targetNamespace = "http://service.example.org/", className = "org.example.client.GetnextResponse")
    @Action(input = "http://service.example.org/Group/getnextRequest", output = "http://service.example.org/Group/getnextResponse")
    public int getnext(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setStudents", targetNamespace = "http://service.example.org/", className = "org.example.client.SetStudents")
    @ResponseWrapper(localName = "setStudentsResponse", targetNamespace = "http://service.example.org/", className = "org.example.client.SetStudentsResponse")
    @Action(input = "http://service.example.org/Group/setStudentsRequest", output = "http://service.example.org/Group/setStudentsResponse")
    public void setStudents(
        @WebParam(name = "arg0", targetNamespace = "")
        List<Student> arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStudents", targetNamespace = "http://service.example.org/", className = "org.example.client.GetStudents")
    @ResponseWrapper(localName = "getStudentsResponse", targetNamespace = "http://service.example.org/", className = "org.example.client.GetStudentsResponse")
    @Action(input = "http://service.example.org/Group/getStudentsRequest", output = "http://service.example.org/Group/getStudentsResponse")
    public String getStudents();

}
